CLIMATE = {
    COLD=1,
    MODERATE_WET=2,
    MODERATE_DRY=3,
    HOT_WET=4,
    HOT_DRY=5,
}

RELIEF = {
    FLAT=1,
    HILLS=2,
    LOW_MOUNTAINS=3,
    HIGH_MOUNTAINS=4,
    SHALLOW_SEA=5,
    DEEP_SEA=6,
}

VEGETATION = {
    NONE=1, -- DESERT or TUNDRA
    GRASS=2,
    LIGHT_FOREST=3,
    DENSE_FOREST=4,
    SWAMP=5,
}

RIVER = {
    BROOK = 1,
    SHALLOW_RIVER = 2,
    MEDIUM_RIVER = 3,
    DEEP_RIVER = 4
}

TERRAIN = {
    -- COLD
    TUNDRA_FLAT = {"Tundra", CLIMATE.COLD, RELIEF.FLAT, VEGETATION.NONE},
    TUNDRA_HILLS = {"Tundra", CLIMATE.COLD, RELIEF.HILLS, VEGETATION.NONE},
    TAIGA_FLAT = {"Taiga", CLIMATE.COLD, RELIEF.FLAT, VEGETATION.DENSE_FOREST},
    TAIGA_HILLS = {"Taiga", CLIMATE.COLD, RELIEF.HILLS, VEGETATION.DENSE_FOREST},
    -- MODERATE_WET
    GRASSLAND = {"Grassland", CLIMATE.MODERATE_WET, RELIEF.FLAT, VEGETATION.GRASS},
    FOREST = {"Forest", CLIMATE.MODERATE_WET, RELIEF.FLAT, VEGETATION.GRASS},
    SWAMP = {"Swamp", CLIMATE.MODERATE_WET, RELIEF.FLAT, VEGETATION.SWAMP},
    HILLS = {"Hills", CLIMATE.MODERATE_WET, RELIEF.HILLS, VEGETATION.GRASS},
    FORESTY_HILLS = {"Foresty hills", CLIMATE.MODERATE_WET, RELIEF.HILLS, VEGETATION.DENSE_FOREST},
    -- MODERATE_DRY
    STEPPE_FLAT = {"Steppe", CLIMATE.MODERATE_DRY, RELIEF.FLAT, VEGETATION.GRASS},
    STEPPE_FOREST = {"Steppe", CLIMATE.MODERATE_DRY, RELIEF.FLAT, VEGETATION.LIGHT_FOREST},
    STEPPE_HILLS = {"Steppe hills", CLIMATE.MODERATE_DRY, RELIEF.HILLS, VEGETATION.GRASS},
    STEPPE_FORESTY_HILLS = {"Steppe foresty hills", CLIMATE.MODERATE_DRY, RELIEF.HILLS, VEGETATION.LIGHT_FOREST},
    -- HOT_WET
    JUNGLE = {"Jungle", CLIMATE.HOT_WET, RELIEF.FLAT, VEGETATION.DENSE_FOREST},
    JUNGLE_HILLS = {"Jungle hills", CLIMATE.HOT_WET, RELIEF.HILLS, VEGETATION.DENSE_FOREST},
    JUNGLE_SWAMP = {"Jungle swamp", CLIMATE.HOT_WET, RELIEF.HILLS, VEGETATION.SWAMP},
    -- HOT DRY
    DESERT = {"Desert", CLIMATE.HOT_DRY, RELIEF.FLAT, VEGETATION.NONE},
    DESERT_DUNES = {"Desert dunes", CLIMATE.HOT_DRY, RELIEF.HILLS, VEGETATION.NONE},
    -- Special
    LOW_MOUNTAINS = {"Low mountains", CLIMATE.MODERATE, RELIEF.LOW_MOUNTAINS, VEGETATION.DENSE_FOREST},
    HIGH_MOUNTAINS = {"High mountains", CLIMATE.COLD, RELIEF.HIGH_MOUNTAINS, VEGETATION.NONE},
}
