{
    "name": "Development Surface",
    "description": "Development world surface for Dawn of Civilizations",
    "tileWidth": 110,
    "tileHeight": 128,
    "banners": {
        "Stripes Horizontal": "banners/stripes_horizontal.png",
        "Stripes Vertical": "banners/stripes_vertical.png",
        "Bicolor Horizontal": "banners/bicolor_horizontal.png",
        "Bicolor Vertical": "banners/bicolor_vertical.png"
    },
    "colors": {
        "Black": "black",
        "Blue": "blue",
        "Cyan": "cyan",
        "Green": "green",
        "Grey": "grey",
        "Magenta": "magenta",
        "Orange": "orange",
        "Purple": "purple",
        "Red": "red",
        "White": "white",
        "Yellow": "yellow"
    }
}
