{
    "name": "Development Surface",
    "description": "Development world surface for Dawn of Civilizations",
    "tileSize": 128,
    "gridSize": 32,
    "rulesEntryPoint": "dev.lua",
    "rulesType": "Lua",
    "banners": {
        "Stripes Horizontal": "banners/stripes_horizontal.png",
        "Stripes Vertical": "banners/stripes_vertical.png",
        "Bicolor Horizontal": "banners/bicolor_horizontal.png",
        "Bicolor Vertical": "banners/bicolor_vertical.png"
    },
    "colors": {
        "Black": "black",
        "Blue": "blue",
        "Cyan": "cyan",
        "Green": "green",
        "Grey": "grey",
        "Magenta": "magenta",
        "Orange": "orange",
        "Purple": "purple",
        "Red": "red",
        "White": "white",
        "Yellow": "yellow"
    },
    "graphicAssets": {
        "terrain_flat_center": "terrain/flat.png",
        "terrain_flat_side": "terrain/flat.png",
        "terrain_hills_center": "terrain/hills-center.png",
        "terrain_hills_side": "terrain/hills-side.png",
        "terrain_mountains_center": "terrain/mountains-center.png",
        "terrain_mountains_side": "terrain/mountains-side.png"
    }
}
